[package]
name = "simple-sat-solver"
version = "0.1.0"
authors = ["Lasse <lasse.moeldrup@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
rustflags = "-C target-cpu=native"

[dependencies]
